### ISSUE TITLE
Power-ups

### ISSUE THREAD

**Issue by mkapal** [mkapal/lfs-power-ups#7]
Power-ups are special autocross objects spawned at random places on track. They can be distinguished by a colour.

If you drive over them, one of the random features gets activated.

## Instant power-ups

- [x] #5
- [x] #6
- [ ] Must stop the car in a time limit to get bonus points
- [ ] Must not go below certain speed to get extra points
- [ ] Must not hit anyone in the next X seconds to get bonus points
- [ ] Random points bonus
- [ ] Car health bonus
- [ ] Lucky dog (get a lap back if one or more laps behind)
- [ ] Mass handicap for X seconds
- [ ] Cars within a certain distance behind will gain points for X seconds

## Manual power-ups

Activation command: `/i powerup`

- [ ] #4 
- [ ] Spawn a fake power-up behind
